### ISSUE TITLE
Design Doc Checklist

### ISSUE THREAD

**Issue by KevinHJo** [pierrenav13/lax#1]
# Wiki Page Home
- [ ] Is the first page you see upon entering the wiki
- [x] Contains a welcome message
- [ ] Contains a link/placeholder for a link to the live page
- [ ] All links in the right sidebar should contain each wiki page and link to the correct page
- [ ] Correctly formatted
    - [ ] each wiki page is listed in bullet points
    - [ ] all links route the correct page
## Comments
- This is where the table of contents for your wiki pages should be

---
# MVP List
- [ ] Should have 7 MVPs.
    - [ ] 3 of those are User Auth, Heroku, and Production README.
    - [x] The other 4 are from the [MVP List](https://github.com/appacademy/curriculum/blob/master/full-stack-project/proposal/mvp-list.md) or they have clarified them with you
- [ ] Contains a description sentence of the app
- [ ] Includes two to three detailed bullets on functionality and presentation of feature
- [ ] At least one CRUD feature, which states what CRUD operations are planned (creation, reading, updating, deletion)
- [ ] Estimates how long it will take the code each MVP
- [ ] Correctly formatted
    - [ ] MVPs are listed in an ordered list
    - [ ] Each MVP is broken down into bullet points
## Comments

- Need to include User Auth, Heroku deployment, and Production README
- Format the MVPs in an ordered list
- Include estimated time to complete each MVP
- Include bullet points to describe each MVP

---
